### ISSUE TITLE
Run error for pillowfight SWT

### ISSUE THREAD

**Issue by SudhenduP** [jflesch/libpillowfight#3]
Hi,

Firstly, thanks for the wonderful package. I have been looking for SWT implementation in Python and this looks to be promising. Unfortunately, I am facing the following error while running one of the example.

Here is my code:

import pillowfight
from matplotlib import pyplot as plt

```
img_in='my_imagefile.jpg'
img_out = pillowfight.swt(img_in, output_type=pillowfight.SWT_OUTPUT_BW_TEXT)
plt.imshow(img_out),plt.colorbar(),plt.show()
```

Below is the error:

> Traceback (most recent call last):
  File "C:/Users/sudhpandey/Documents/MachineLearning/Projects/BIBDetectionPython3/expillowfight.py", line 8, in <module>
    output_type=pillowfight.SWT_OUTPUT_BW_TEXT)
  File "C:\Users\sudhpandey\AppData\Local\Programs\Python\Python35\lib\site-packages\pillowfight\__init__.py", line 217, in swt
    img_in = img_in.convert("RGBA")  # Add alpha to align on 32bits
AttributeError: 'str' object has no attribute 'convert'

I am sure this error is one of my doing. But I am wondering what could be wrong here?

**Comment by jflesch** [comment]
Hello,

The image given as input to the function is not a string, a path nor a file descriptor. It is a Pillow image (PIL.Image).

Example:

```py
import PIL.Image

img_in = PIL.Image.open('my_imagefile.jpg')
img_out = pillowfight.swt(img_in, output_type=pillowfight.SWT_OUTPUT_BW_TEXT)
img_out.save('my_imagefile.jpg')
```

On Windows, you can get a precompiled version of Pillow from here:
http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by SudhenduP** [comment]
Thanks! Appreciate your response here :) You saved me a hell of a time.

**Comment by SudhenduP** [comment]
This isn't a issue. Just my lack of understanding of the module. Closing this.
